name: Meine CI Pipeline

on: push

env:
  MEINE_VARIABLE: asdk

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
           sudo apt-get update
           sudo apt-get upgrade -y
      - uses: actions/checkout@v1
  
